module.exports.BOAT = 'boat';
module.exports.LOAD = 'load';
module.exports.USER = 'user';
module.exports.MIN_STRING_LENGTH = 2;
module.exports.MIN_BOAT_LENGTH = 0;
module.exports.MAX_BOAT_NAME_LENGTH = 100;
module.exports.MAX_BOAT_TYPE_LENGTH = 25;
module.exports.MAX_BOAT_LENGTH = 1000;
module.exports.NUM_BOAT_ATTRIBUTES = 3;
module.exports.NUM_LOAD_ATTRIBUTES = 2;
module.exports.PAGINATION_LIMIT = 5;
module.exports.EXPRESS_SESSION_COOKIE_EXPIRY = 60000 * 30; // 30 min